### ISSUE TITLE
Where to get credentials 

### ISSUE THREAD

**Issue by vespertilian** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#12]
Hi, 

So I am trying to use this Object Storage in Sydney. I have setup a container but all the tutorials, including the readme here show keys and attributes I cannot seem to find in the interface.

Attributes like - ProjectId, 

I have :
Public: https://syd01.objectstorage.softlayer.net/auth/v1.0/
Private: https://syd01.objectstorage.service.networklayer.com/auth/v1.0/
Username: SLOS1307 etc
API Key
xxxxxxxxx

Lots of tutorials also point to auth at https://identity.open.softlayer.com/ which is different from the urls listed above. 

I also cannot seem to create storage attached to a service - it's not an option in Sydney.

**Comment by rnchamberlain** [comment]
I'm in London not Sydney, but I found those attributes on the Bluemix Dashboard->App->Connections panel. Once I had connected the Object Storage service to my Bluemix instance, there was a 'View credentials' button on  the Object Storage icon.

**Comment by abaruni** [comment]
@vespertilian https://ibm-public-cos.github.io/crs-docs/

You are using either [**IBM COS Cross Region**](https://ibm-public-cos.github.io/crs-docs/#ibm-cos-cross-region) or [**Cloud Object Storage Regional**](https://ibm-public-cos.github.io/crs-docs/#cloud-object-storage-regional)

This sdk will only work with [**Object Storage for IBM Bluemix Developer Services**](https://ibm-public-cos.github.io/crs-docs/#object-storage-for-ibm-bluemix-developer-services) which is only available in London and Dallas. You are not seeing the right credentials because the compatible service is unavailable in Sydney

**Comment by vespertilian** [comment]
@abaruni Thanks for your answer I believe I am using the Cloud Object Storage Regional. I thought it had the same SWIFT api as Object Storage for IBM Bluemix Developer Services? Is there not a library that I can use to work with storage in Sydney?

**Comment by abaruni** [comment]
@vespertilian they both do use the same (confusingly named) Swift API, but it looks like they use different authentication mechanisms and credentials. I don't believe there is a library that supports Object Storage in Sydney at the moment. This one was created before the introduction of the Cross Region and Regional variants
