### ISSUE TITLE
Invalid URI when using local credentials

### ISSUE THREAD

**Issue by steveatkin** [ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#8]
The way the URI is being determined when using local credentials is incorrect. 

In ObjectStorage.js line 22 is incorrect as creds.region only contains the region name and not the URL

 this.baseResourceUrl = creds.region + creds.projectId;

This should be replaced with the following:

this.baseResourceUrl = ((creds.region === 'dallas') ? ObjectStorage.Region.DALLAS : ObjectStorage.Region.LONDON) + creds.projectId;

**Comment by abaruni** [comment]
@steveatkin please see the example usage of the credentials object 

https://github.com/ibm-bluemix-mobile-services/bluemix-objectstorage-serversdk-nodejs#objectstorage

you should be passing in `region: ObjectStorage.Region.DALLAS` **NOT** `region: 'dallas'`

**Comment by rnchamberlain** [comment]
It would be very useful if the API would accept a string, ie 'dallas' as an alternative to ObjectStorage.Region.DALLAS:

1. Usability: the credentials that are shown when using Bluemix Connections panel and the 'View credentials' button on the Object Storage icon, list 'dallas'. So users will very likely copy that, as the other attributes, then hit the failure.

2. ObjectStorage.Region.DALLAS necessitates a statement like `var ObjectStorage = require('bluemix-objectstorage').ObjectStorage; `- otherwise `'ObjectStorage`' is undefined. All the other required attributes are just strings.

**Comment by abaruni** [comment]
@rnchamberlain 

1) The correct usage is documented in the README and given the distinct and limited number of regions, an enumeration is the natural choice

2) This is going to be required in order to use the sdk anyway
